import fs from "fs";
import { createClient } from "@supabase/supabase-js";
const env = Object.fromEntries(fs.readFileSync(".env","utf8").split(/\r?\n/).filter(l=>l.includes("=")&&!l.startsWith("#")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i).trim(), l.slice(i+1).trim().replace(/^["']|["']$/g,"")]}));
const db = createClient(env.VITE_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);
const { data: p } = await db.from("pay_profiles").select("*");
console.log(JSON.stringify(p?.map(x=>({u:x.user_id.slice(0,8),base:x.base_salary,bhxh:x.social_insurance,union:x.union_fee,rate:x.commission_rate,in:x.in_payroll,tech:x.tech_revenue})),null,0));
const { data: per } = await db.from("payroll_periods").select("*");
console.log(JSON.stringify(per));
const { data: it } = await db.from("payroll_items").select("*");
console.log(JSON.stringify(it));
